### ISSUE TITLE
Link to event using NIP-21

### ISSUE THREAD

**Issue by fiatjaf** [verbiricha/ngine#1]
I'm browsing https://nostrrr.com/ and I want to interact with some of the events I see there, but I can't find a way to click on them and be redirected to some other client where I can do that. Would be nice to have a `nostr:nevent...` link somewhere, maybe in the event date?

**Comment by verbiricha** [comment]
The event footers have a three dots menu where you can copy the ID but perhaps is not very obvious. I think I should add a "Open" menu on the event header to all events that lets you open it in another app using NIP-89, wdyt?

**Comment by fiatjaf** [comment]
That would be nice too, but I was asking just for the `nostr:` link as that would work for me since I have a handler for it already configured and I thought would be simple (well, not so simple as I tried to implement it myself but failed).

I guess that could be the first option in the menu that lists other apps using NIP-89 or something like that.

**Comment by verbiricha** [comment]
Added raw nostr link as the first option and included the event menu for notes and long form posts.
