### ISSUE TITLE
[emojito] emoji set (30030) can be created with "Emoji set name" (d tag, title tag) empty

### ISSUE THREAD

**Issue by Lokuyow** [verbiricha/ngine#4]
### How to reproduce
- Access the New emoji set page
- Enter shortcode and image URL
- "Save" without entering Emoji set name

### Result

Example:

`{
  "created_at": 1707348881,
  "content": "",
  "tags": [
    [
      "d",
      ""
    ],
    [
      "title",
      ""
    ],
    [
      "emoji",
      "test",
      "https://raw.githubusercontent.com/Lokuyow/Lokuyow.github.io/main/images/nostr/emoji/test.png"
    ]
  ],
  "kind": 30030,
  "pubkey": "ec42c765418b3db9c85abff3a88f4a3bbe57535eebbdc54522041fa5328c0600",
  "id": "1c43218c62d9d8e7889a2319e6a4b8f17a1e5e5771b66cc066090a30ad6d6b77",
  "sig": "42a71dbedfbb587162f7fc1180bdb738017a5cc6a0b5e34039d1c2eb302e8548cbd50220b7ed20fff94a11d71bd1658e71d91c9d6304bcc97df8b89af74adcb3"
}`

**Comment by verbiricha** [comment]
Thanks for reporting, fixed!
